### ISSUE TITLE
Cmd+Shift+T does not work if browsing Twitter or Google Docs 

### ISSUE THREAD

**Issue by bucaran** [bucaran/retab#3]
But why.

**Comment by krisdestruction** [comment]
I can reproduce it when a doc is open. Check out the [keyboard shortcuts for gDrive](https://support.google.com/docs/answer/179738?hl=en). Basically a lot of things hook into `cmd + Shift + T` (just do a search for "Shift + T" after opening the mac section. It'd be nice if the extension can escape this or something...

**Comment by bucaran** [comment]
@krisdestruction Thanks! Will check.

**Comment by krisdestruction** [comment]
@bucaran I should note that this doesn't work on Facebook too if you use that. FB and gDrive both hook into keyboard shortcuts and although there might not be any actual mapping, I think the code they use captures all keys except normal ones.

**Comment by bucaran** [comment]
I have no idea how to fix this one, but here is the good news: `Cmd+Z` is always available, so I would just use it to reopen any closed tab if you are browsing Twitter / Facebook, and after that one I would use `Ctrl+Shift+T` normally.
