### ISSUE TITLE
Reopening Tabs Requires Page Load

### ISSUE THREAD

**Issue by krisdestruction** [bucaran/retab#4]
If you open 10 youtube tabs (since youtube has media, it's slow to load), close them, and reopen them by spamming Cmd + Shift + Tab 10 times, it doesn't all open when you press the button. The page has to partially load before the Cmd + Shift + Tab is responsive again.

Forked from #2.

**Comment by bucaran** [comment]
Thanks. I will have a look at this.

**Comment by krisdestruction** [comment]
What does your help wanted label mean? You need help isolating the issue, testing, or coding?

**Comment by bucaran** [comment]
It just a simple way to say that if anyone can help in any way it would be appreciated and well received.

**Comment by bucaran** [comment]
Done b3c089b

Now you can choose to reopen tabs in the background for warp speed. Foreground opening is now an option under `Settings`.

**Comment by krisdestruction** [comment]
Awesome! I assume this still needs to be put through the Apple app approval queue? I don't think there's an update for the extension yet.

**Comment by bucaran** [comment]
Good point. I figured the bundle would get automatically updated given there is an `Update.plist` manifest , but maybe it requires submitting the app again?

**Comment by krisdestruction** [comment]
Perhaps? I mean I don't mind reinstalling, but I can stay here to help test if your app auto updated. Maybe emailing Apple support or checking online would be a good idea. Let me know what action I can take to help you out!

**Comment by bucaran** [comment]
I updated the manifest, and resubmitted to Apple anyway :smile: 

Thanks!

**Comment by krisdestruction** [comment]
I still don't see the update. It might be in the approval queue. Should I wait and report back if I still don't see an update within the week?
