### ISSUE TITLE
History On Reopened Tab

### ISSUE THREAD

**Issue by krisdestruction** [bucaran/retab#6]
Not quite sure if it's a bug or should be a feature request. Reopened tabs lose the history in the back button. Not sure if it's possible, but it'd be great if it could restore the history in the back tab.

It should be easy to reproduce, but let me know if you need a test case.

**Comment by bucaran** [comment]
Useful to have indeed. Closing in favor of #1 

I definitely want to add this functionality.

**Comment by krisdestruction** [comment]
Oh sorry I forgot to search the issues. Thanks!
