### ISSUE TITLE
Downloadable version still at 1.0

### ISSUE THREAD

**Issue by grettir** [bucaran/retab#8]
The download links for Retab are still pointing to a build of version 1.0. This leads to an endless download/update loop within Safari.

Step 1: The extension checks to see if an update is available here:

```
https://raw.githubusercontent.com/bucaran/retab/master/Updates.plist
```

Step 2: It sees that version 1.1 is available and downloads/installs the supposedly updated version from here:

```
https://github.com/bucaran/retab/blob/master/retab.safariextz?raw=true
````

Unfortunately, that just re-downloads and re-installs version 1.0.

Step 3: Rinse and repeat.

**Comment by bucaran** [comment]
Thanks!

I will be releasing a new 2.0 version in a few minutes fixing most bugs reported in the issues as well as updating the `.plist` file.

**Comment by bucaran** [comment]
![icon](https://cloud.githubusercontent.com/assets/8317250/7451539/caffc5aa-f28c-11e4-9c7e-f3a79931a256.png)

**Comment by bucaran** [comment]
Fixed in GitHub and resubmitted to Apple.
