### ISSUE TITLE
download link takes you to a 404 page

### ISSUE THREAD

**Issue by trusk89** [bucaran/retab#9]

**Comment by mileswd** [comment]
The extension archive was deleted in 1ae03982faf6f794571f14f2921ae60caf5ca75f

It may be an older build, but it is still accessible here: https://github.com/bucaran/retab/blob/b3c089bdf70fe2ec663a1e6e020aa1b3048b8894/retab.safariextz?raw=true

**Comment by bucaran** [comment]
Fixed.

[Bundle download link](https://github.com/bucaran/retab/blob/master/retab.safariextz?raw=true)
